version: "3.8"

services:
  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app-a
      - app-b
      - app-blue
      - app-green
    networks:
      - TESLA-net
    restart: unless-stopped

  app-base:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    expose:
      - "8501"
    networks:
      - TESLA-net

  app-a:
    extends: app-base
    hostname: app-a
    command: streamlit run app.py --server.port 8501 --server.headless true

  app-b:
    extends: app-base
    hostname: app-b
    command: streamlit run app_b.py --server.port 8502 --server.headless true
    expose:
      - "8502"

  app-blue:
    extends: app-base
    hostname: app-blue
    command: streamlit run app.py --server.port 8503 --server.headless true
    expose:
      - "8503"

  app-green:
    extends: app-base
    hostname: app-green
    command: streamlit run app.py --server.port 8504 --server.headless true
    expose:
      - "8504"

networks:
  TESLA-net:
    driver: bridge

volumes:
  certs:
